### PR TITLE
feat(core): improving component scan of package #4

### PR DESCRIPTION
**Pull request by ahmadshabib**

### CODE REVIEW

**Review by alex-agathocleous — COMMENTED** [review]
Why go from spring boot to spring cloud?

**Comment by ahmadshabib** [comment]
> Why go from spring boot to spring cloud?

The library had an unnecessary dependency on spring boot which should not be the case therefore I removed it, we only need to depend on spring cloud as it allows us to do the sqs connection.

**Review by Mantas-Gav — COMMENTED** [review]
any functionality changes here, or is this so it's more efficient/some other background improvement?

**Comment by ahmadshabib** [comment]
> any functionality changes here, or is this so it's more efficient/some other background improvement?

with this, we don't need to add @ComponentScan on top of our spring applications, it would do autoconfig

**Review by Mantas-Gav — APPROVED** [review]

**Pull request merged**
